pipeline {
    agent any

    stages {

        stage('Build Docker Images') {
            steps {
                dir('farmer-market-portal') {
                    sh 'docker compose build'
                }
            }
        }

        stage('Run Containers') {
            steps {
                dir('farmer-market-portal') {
                    sh 'docker compose up -d'
                }
            }
        }
    }
}
